--- #YAML:1.0
name:               LWP-Authen-OAuth2
version:            0.03
abstract:           Make requests to OAuth2 APIs.
author:
    - Ben Tilly <btilly@gmail.com>
license:            Artistic_2_0
distribution_type:  module
configure_requires:
    ExtUtils::MakeMaker:  0
build_requires:
    Test::More:  0
requires:
    JSON:                 2
    LWP:                  4
    LWP::Protocol::https:  6
    Mozilla::CA:          20000101
    perl:                 5.006
no_index:
    directory:
        - t
        - inc
generated_by:       ExtUtils::MakeMaker version 6.56
meta-spec:
    url:      http://module-build.sourceforge.net/META-spec-v1.4.html
    version:  1.4
